version: '2'

services:
  server:
    build: ./Server
    container_name: lilly-server
    restart: always
    ports:
      - "50051:50051" 

  client:
    build: ./Telegramclient
    container_name: lilly-telegram
    restart: always
    environment:
      SERVER: server
    links:
      - server
    depends_on:
      - server
