# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/grpc/pb/message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/grpc/pb/message.proto',
  package='proto.src.grpc.pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19src/grpc/pb/message.proto\x12\x11proto.src.grpc.pb\"\x1e\n\x0eMessageRequest\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t\"\x1f\n\x0fMessageResponse\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t2\xc1\x01\n\x07Message\x12X\n\rSingleRequest\x12!.proto.src.grpc.pb.MessageRequest\x1a\".proto.src.grpc.pb.MessageResponse\"\x00\x12\\\n\rStreamRequest\x12!.proto.src.grpc.pb.MessageRequest\x1a\".proto.src.grpc.pb.MessageResponse\"\x00(\x01\x30\x01\x62\x06proto3')
)




_MESSAGEREQUEST = _descriptor.Descriptor(
  name='MessageRequest',
  full_name='proto.src.grpc.pb.MessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='proto.src.grpc.pb.MessageRequest.body', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=78,
)


_MESSAGERESPONSE = _descriptor.Descriptor(
  name='MessageResponse',
  full_name='proto.src.grpc.pb.MessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='proto.src.grpc.pb.MessageResponse.body', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['MessageRequest'] = _MESSAGEREQUEST
DESCRIPTOR.message_types_by_name['MessageResponse'] = _MESSAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessageRequest = _reflection.GeneratedProtocolMessageType('MessageRequest', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEREQUEST,
  __module__ = 'src.grpc.pb.message_pb2'
  # @@protoc_insertion_point(class_scope:proto.src.grpc.pb.MessageRequest)
  ))
_sym_db.RegisterMessage(MessageRequest)

MessageResponse = _reflection.GeneratedProtocolMessageType('MessageResponse', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGERESPONSE,
  __module__ = 'src.grpc.pb.message_pb2'
  # @@protoc_insertion_point(class_scope:proto.src.grpc.pb.MessageResponse)
  ))
_sym_db.RegisterMessage(MessageResponse)



_MESSAGE = _descriptor.ServiceDescriptor(
  name='Message',
  full_name='proto.src.grpc.pb.Message',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=114,
  serialized_end=307,
  methods=[
  _descriptor.MethodDescriptor(
    name='SingleRequest',
    full_name='proto.src.grpc.pb.Message.SingleRequest',
    index=0,
    containing_service=None,
    input_type=_MESSAGEREQUEST,
    output_type=_MESSAGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StreamRequest',
    full_name='proto.src.grpc.pb.Message.StreamRequest',
    index=1,
    containing_service=None,
    input_type=_MESSAGEREQUEST,
    output_type=_MESSAGERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSAGE)

DESCRIPTOR.services_by_name['Message'] = _MESSAGE

# @@protoc_insertion_point(module_scope)
